// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCleanup(arg1) {
  return window['go']['main']['App']['ExecuteCleanup'](arg1);
}

export function GetDirectoryInsight(arg1) {
  return window['go']['main']['App']['GetDirectoryInsight'](arg1);
}

export function GetDiskInfo(arg1) {
  return window['go']['main']['App']['GetDiskInfo'](arg1);
}

export function GetFilesByExt(arg1, arg2) {
  return window['go']['main']['App']['GetFilesByExt'](arg1, arg2);
}

export function GetSecurityAudit() {
  return window['go']['main']['App']['GetSecurityAudit']();
}

export function GetTopFiles(arg1) {
  return window['go']['main']['App']['GetTopFiles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LocateFile(arg1) {
  return window['go']['main']['App']['LocateFile'](arg1);
}

export function ScanCleanup(arg1) {
  return window['go']['main']['App']['ScanCleanup'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
