// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteCleanup(arg1:Array<string>):Promise<void>;

export function GetDirectoryInsight(arg1:string):Promise<main.DirInsight>;

export function GetDiskInfo(arg1:string):Promise<main.DiskInfo>;

export function GetFilesByExt(arg1:string,arg2:string):Promise<Array<main.FileStat>>;

export function GetFilesByExts(arg1:string,arg2:Array<string>):Promise<Array<main.FileStat>>;

export function GetLastPath():Promise<string>;

export function GetSecurityAudit():Promise<Array<Record<string, any>>>;

export function GetTopFiles(arg1:string):Promise<Array<main.FileStat>>;

export function Greet(arg1:string):Promise<string>;

export function LocateFile(arg1:string):Promise<void>;

export function SaveLastPath(arg1:string):Promise<void>;

export function ScanCleanup(arg1:string):Promise<Array<main.FileStat>>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<main.FileStat>>;

export function SelectFolder():Promise<string>;

export function StartAutoMonitor(arg1:string):Promise<void>;
